import { Renderer } from "@freelensapp/extensions";
import styles from "./views.module.css";

const {
  Component: { Button, Icon },
} = Renderer;

export interface SubmittedObject {
  kind: string;
  apiVersion: string;
  // The name it will have, or the prefix of the name the API server generates.
  name: { exact: string } | { prefix: string };
  namespace: string;
  // The cluster as the host names it, and its context.
  cluster: string;
  context: string;
  labels: Readonly<Record<string, string>>;
  // The spec in words.
  spec: string;
  // The target in words, or that there is none.
  target: string;
}

// The confirmation of one write, inline where the write is offered: the object as it will be submitted,
// and the second gesture, which is the one the token of the main process stands for. Nothing is created
// before it. It can be given the focus, which is how the keyboard and who does not see get to it when it
// takes the place of the command that asked for it; the focus is not on the command that creates, so that
// the key that asked is not the one that confirms.
export function WriteConfirmation({
  id,
  object,
  onCreate,
  onBack,
}: {
  id: string;
  object: SubmittedObject;
  onCreate: () => void;
  onBack: () => void;
}) {
  const fields: [string, string, string][] = [
    ["kind", "Kind", `${object.kind} (${object.apiVersion})`],
    [
      "name",
      "Name",
      "exact" in object.name ? object.name.exact : `Generated by the API server, beginning with ${object.name.prefix}`,
    ],
    ["namespace", "Namespace", object.namespace],
    ["cluster", "Cluster", `${object.cluster} (context ${object.context})`],
    [
      "labels",
      "Labels",
      Object.entries(object.labels)
        .map(([key, value]) => `${key}=${value}`)
        .join(", ") || "None",
    ],
    ["spec", "Spec", object.spec],
    ["target", "Target", object.target],
  ];

  return (
    <section
      className={styles.writeConfirmation}
      data-testid={id}
      aria-label={`The ${object.kind} that will be created`}
      tabIndex={-1}
    >
      <p className={styles.stateText}>This {object.kind} will be created when you confirm, and not before:</p>
      <dl className={styles.writeObject}>
        {fields.map(([field, name, value]) => (
          <div key={field} data-field={field}>
            <dt className={styles.factName}>{name}</dt>
            <dd className={styles.factValue}>{value}</dd>
          </div>
        ))}
      </dl>
      <div className={styles.writeActions}>
        <Button primary data-testid={`${id}-create`} onClick={onCreate}>
          <Icon material="check" small />
          Create the {object.kind}
        </Button>
        <Button plain data-testid={`${id}-back`} onClick={onBack}>
          <Icon material="close" small />
          Do not create it
        </Button>
      </div>
    </section>
  );
}
