// @vitest-environment jsdom

import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { WriteConfirmation } from "./write-confirmation";

import type { SubmittedObject } from "./write-confirmation";

const OBJECT: SubmittedObject = {
  kind: "DownloadRequest",
  apiVersion: "velero.io/v1",
  name: { exact: "backup-a-0f7c" },
  namespace: "velero-a",
  cluster: "local-demo",
  context: "kind-local-demo",
  labels: {},
  spec: "The log of the backup",
  target: "The backup backup-a",
};

const facts = () =>
  Object.fromEntries(
    [...screen.getByTestId("write").querySelectorAll("[data-field]")].map((field) => [
      field.getAttribute("data-field"),
      [field.querySelector("dt")?.textContent, field.querySelector("dd")?.textContent],
    ]),
  );

afterEach(cleanup);

describe("the confirmation of one write", () => {
  it("shows the object as it will be submitted: a name that is given, and that it has no labels", () => {
    render(<WriteConfirmation id="write" object={OBJECT} onCreate={() => undefined} onBack={() => undefined} />);
    expect(screen.getByTestId("write").getAttribute("aria-label")).toBe("The DownloadRequest that will be created");
    expect(facts()).toEqual({
      kind: ["Kind", "DownloadRequest (velero.io/v1)"],
      name: ["Name", "backup-a-0f7c"],
      namespace: ["Namespace", "velero-a"],
      cluster: ["Cluster", "local-demo (context kind-local-demo)"],
      labels: ["Labels", "None"],
      spec: ["Spec", "The log of the backup"],
      target: ["Target", "The backup backup-a"],
    });
  });

  it("shows the prefix of a name the API server generates, and every label", () => {
    render(
      <WriteConfirmation
        id="write"
        object={{ ...OBJECT, name: { prefix: "synthetic-" }, labels: { one: "a", two: "b" } }}
        onCreate={() => undefined}
        onBack={() => undefined}
      />,
    );
    expect(facts().name).toEqual(["Name", "Generated by the API server, beginning with synthetic-"]);
    expect(facts().labels).toEqual(["Labels", "one=a, two=b"]);
  });

  it("creates with its first command and is left with its second, each once", () => {
    const onCreate = vi.fn();
    const onBack = vi.fn();

    render(<WriteConfirmation id="write" object={OBJECT} onCreate={onCreate} onBack={onBack} />);
    expect(onCreate).not.toHaveBeenCalled();
    fireEvent.click(screen.getByTestId("write-create"));
    expect([onCreate.mock.calls.length, onBack.mock.calls.length]).toEqual([1, 0]);
    fireEvent.click(screen.getByTestId("write-back"));
    expect([onCreate.mock.calls.length, onBack.mock.calls.length]).toEqual([1, 1]);
  });

  it("is left with Escape, which what holds it does not take for its own", () => {
    const onBack = vi.fn();
    const held = vi.fn();

    render(
      // biome-ignore lint/a11y/noStaticElementInteractions: what holds the confirmation, which listens to the keys as a page of the host does
      <div onKeyDown={held}>
        <WriteConfirmation id="write" object={OBJECT} onCreate={() => undefined} onBack={onBack} />
      </div>,
    );
    fireEvent.keyDown(screen.getByTestId("write-create"), { key: "Tab" });
    expect([onBack.mock.calls.length, held.mock.calls.length]).toEqual([0, 1]);
    fireEvent.keyDown(screen.getByTestId("write-create"), { key: "Escape" });
    expect([onBack.mock.calls.length, held.mock.calls.length]).toEqual([1, 1]);
  });
});
